apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk1
  namespace: ashuwebapp # this line added 
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi