apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashuapp_db
  name: ashuapp-db
  namespace: ashuwebapp
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: ashuapp_db
  type: ClusterIP
status:
  loadBalancer: {}
